/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcquizmt;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static kbcquizmt.manageAdminAccount.dataadmin;

/**
 *
 * @author ASUS
 */
public class resultFormManage extends javax.swing.JFrame {
    private static Connection conn;
    DefaultTableModel tb = new DefaultTableModel();

    /**
     * Creates new form resultFormManage
     */
    public resultFormManage() {
        initComponents();
        setIcon();
        load();
        getHeader();
        totalPrize();
        totalNumberOfPlayed();
    }
     public void getHeader(){
        JTableHeader tb = dataResult.getTableHeader();
        tb.setForeground(Color.black);
        
       tb.setFont(new Font("Time New Roman",Font.PLAIN,18));
    }
    public void load(){
        
        try{
            
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=KBCQuizDatabase;integratedSecurity=true;");
          
           Statement st1 = conn.createStatement();
           ResultSet rs1 = st1.executeQuery("select * from  Result");
           if(rs1.next()){
              
           }
           int number;
           Vector row, column;
           column = new Vector();
           Statement st = conn.createStatement();
           ResultSet rs= st.executeQuery("select p.Testid,r.Resultid, Playername ,Prizemoney,QuantityAnsRight  from PlayGame p ,Result r where p.Testid = r.Testid");
           ResultSetMetaData metadata= rs.getMetaData();
           number = metadata.getColumnCount();
           for(int i = 1;i<=number;i++){
               column.add(metadata.getColumnName(i));
           }
           tb.setColumnIdentifiers(column);
           while(rs.next()){
               row = new Vector();
               for(int i=1;i<=number;i++){
                  row.addElement(rs.getString(i));
               }
               tb.addRow(row);
               dataResult.setModel(tb);
           }          
       }
       catch(Exception e){
           System.out.println(e.getMessage());
       }
    }
    private static void totalNumberOfPlayed(){
           DecimalFormat df = new DecimalFormat("#,##0.##");

        int numberOP;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=KBCQuizDatabase;integratedSecurity=true;");
          String select ="select count(Resultid) 'NumberOfPlayed' from Result";
           PreparedStatement pst = conn.prepareStatement(select);
          ResultSet rs = pst.executeQuery();
          while(rs.next()){
              numberOP = rs.getInt(1);
              System.out.println(numberOP);
             number.setText(df.format(numberOP)+ "");
          }
        }
        catch(Exception e){
            
        }
    }
  
    private static void totalPrize(){
               DecimalFormat df = new DecimalFormat("$#,##0.##");
          
       String prize;
       int trans;
       int total=0;
        try{
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=KBCQuizDatabase;integratedSecurity=true;");
          String select ="select  * from Result";
          PreparedStatement pst = conn.prepareStatement(select);
          ResultSet rs = pst.executeQuery();
          while(rs.next()){
              prize = rs.getString(3);
             String p1=prize.substring(1);
                 trans=Integer.parseInt(p1.replace(",", ""));
                   System.out.println(trans);
                   total+=trans;
                   System.out.println("Total :"+total);
                  String  trans1 = df.format(total);
                  prizeM.setText(trans1);
                   
          }
        }
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataResult = new javax.swing.JTable();
        menu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prizeM = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KBC Quiz");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        jPanel2.setBackground(new java.awt.Color(255,255,255,150
        ));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataResult.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dataResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataResult.setFocusable(false);
        dataResult.setIntercellSpacing(new java.awt.Dimension(2, 2));
        dataResult.setRowHeight(20);
        dataResult.setSelectionBackground(new java.awt.Color(153, 255, 153));
        dataResult.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(dataResult);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, 170));

        menu.setBackground(new java.awt.Color(153, 255, 153));
        menu.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menu.setText("Back menu");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel2.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setText("Statistical");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 140, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 950, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("The total amount the player has won:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, 30));

        prizeM.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(prizeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 620, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Total number of plays:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, -1));

        number.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 720, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel3.setText("Information result of player");
        jPanel4.add(jLabel3);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 950, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assset/sky1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
       new menuAdmin().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultFormManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultFormManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultFormManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultFormManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultFormManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable dataResult;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private static javax.swing.JLabel number;
    private static javax.swing.JLabel prizeM;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logokbcquiz2.png")));
    }
}
